/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.30
 * Generated at: 2016-05-10 04:51:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Petition Classes</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id =\"wrapperHeader\">\r\n");
      out.write("<div id= \"header\">\r\n");
      out.write("<img src =\"Images/ust.JPG\" alt = \"Missing Image!=\" width = 1350 height= >\r\n");
      out.write("</div>\r\n");
      out.write("</div> \r\n");
      out.write("<form action=\"login.jsp\" method=\"post\"> <br/>\r\n");
      out.write("<center><p>Username</p><input type=\"text\" name=\"username\"> <br/></center>\r\n");
      out.write("<center><p>Password</p><input type=\"password\" name=\"password\"> <br/>\r\n");
      out.write("<br><input type=\"submit\" value=\"Log in\"> </form> </center>\r\n");
      out.write("\r\n");
      out.write("<style> \r\n");
      out.write("  input[type=\"text\"] { \r\n");
      out.write("    background: #A9A9A9; \r\n");
      out.write("    border: 1px double black; \r\n");
      out.write("    border-radius: 5px; \r\n");
      out.write("    box-shadow: 0 0 5px yellow; \r\n");
      out.write("    color: black; \r\n");
      out.write("    outline: center; \r\n");
      out.write("    height:25px; \r\n");
      out.write("    width: 275px; \r\n");
      out.write("    font-family:\"verdana\";\r\n");
      out.write("  } \r\n");
      out.write("\r\n");
      out.write("p{\r\n");
      out.write("\tfont-family: \"verdana\";\r\n");
      out.write("\talignment: left;\r\n");
      out.write("\t}\r\n");
      out.write("input[type=\"submit\"]{\r\n");
      out.write("    background: #87CEFA; \r\n");
      out.write("    border: 1px double #DDD; \r\n");
      out.write("    border-radius: 5px; \r\n");
      out.write("    box-shadow: 0 0 5px #333; \r\n");
      out.write("    color: ; \r\n");
      out.write("    outline: none; \r\n");
      out.write("    height:25px; \r\n");
      out.write("    width: 100px;\r\n");
      out.write("    font-family: \"verdana\";\r\n");
      out.write("    font-color: black;\r\n");
      out.write("}\r\n");
      out.write("input[type=\"password\"]{\r\n");
      out.write("background: #A9A9A9; \r\n");
      out.write("    border: 1px double black; \r\n");
      out.write("    border-radius: 5px; \r\n");
      out.write("    box-shadow: 0 0 5px yellow; \r\n");
      out.write("    color: black; \r\n");
      out.write("    outline: center; \r\n");
      out.write("    height:25px; \r\n");
      out.write("    width: 275px; \r\n");
      out.write("    font-family:\"verdana\";\r\n");
      out.write("}\r\n");
      out.write("input.remove{\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
