/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.30
 * Generated at: 2016-05-17 10:10:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class remove2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Petition Class</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<form action =\"home.jsp\" method = \"post\">\r\n");
      out.write("<img src =\"Images/ust.JPG\" alt = \"Missing Image!=\" width = 1350 height= ><br>\r\n");
      out.write("<input type=\"submit\" name=\"one\" id=\"remove\" value=\"Schedule\" style=\"width:33%\" style=\"height:15%\"/>\r\n");
      out.write("<input type=\"submit\" name=\"two\" id=\"remove\" value=\"Create A Petition Class\" style=\"width:33%\" style=\"height:15%\"/>\r\n");
      out.write("<input type=\"submit\" name=\"three\" id=\"remove\" value=\"Log out\" style=\"width:33%\" style=\"height:15%\"/></form>\r\n");
 if (request.getParameter("one") != null) {
    response.sendRedirect("home.jsp");
}
else if (request.getParameter("two") != null) {
    response.sendRedirect("create.jsp");
}
else if (request.getParameter("three") != null) {
    response.sendRedirect("index.jsp");
}
else if (request.getParameter("rone") != null){
	response.sendRedirect("remove1.jsp");
}
else if (request.getParameter("rtwo") != null){
	response.sendRedirect("remove2.jsp");
}
else if (request.getParameter("rthree") != null){
	response.sendRedirect("remove3.jsp");
}
else if (request.getParameter("rfour") != null){
	response.sendRedirect("remove4.jsp");
}
else if (request.getParameter("rfive") != null){
	response.sendRedirect("remove5.jsp");
}
else if (request.getParameter("rsix") != null){
	response.sendRedirect("remove6.jsp");
}
else if (request.getParameter("rone") != null){
	response.sendRedirect("remove1.jsp");
}
else if (request.getParameter("rone") != null){
	response.sendRedirect("remove1.jsp");
}
else if (request.getParameter("rone") != null){
	response.sendRedirect("remove1.jsp");
} 
      out.write("\r\n");
      out.write("\r\n");
      out.write("<br>\r\n");
      out.write("<table border=\"1\" align=\"right\" style =\"width: 20%\">\r\n");
      out.write("<tr>\r\n");
      out.write("<th> Available Schedule </th>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>(2 Units)PHY M 7-8 W 8-9</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td><form><input type=\"submit\" name=\"two\" value=\"Add schedule to subjects\"/></form></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td> (2 Units)APP M 7-8 W 8-9 </td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td> <form><input type=\"submit\" name=\"two\" value=\"Add schedule to subjects\"/></form></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>(3 Units) IS 206 M 7-10</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td> <form><input type=\"submit\" name=\"two\" value=\"Add schedule to subjects\"/></form></td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("<table border=\"1\" style =\"width: 75%\">\r\n");
      out.write("<tr>\r\n");
      out.write("<th> Subject </th>\r\n");
      out.write("<th> Subject Description</th>\r\n");
      out.write("<th> Lec Units</th>\r\n");
      out.write("<th> Lab Units</th>\r\n");
      out.write("<th> Section</th>\r\n");
      out.write("<th> Schedule </th>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>ENG 1</td>\r\n");
      out.write("<td> Subject Description </td>\r\n");
      out.write("<td>3</td>\r\n");
      out.write("<td>Lab Units</td>\r\n");
      out.write("<td>Section</td>\r\n");
      out.write("<td>Schedule</td>\r\n");
      out.write("<td><form><input type=\"submit\"  name=\"rone\" value=\"Remove\" style=\"width:100%\"></form></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>PHL 1</td>\r\n");
      out.write("<td> Subject Description </td>\r\n");
      out.write("<td>3</td>\r\n");
      out.write("<td>Lab Units</td>\r\n");
      out.write("<td>Section</td>\r\n");
      out.write("<td>Schedule</td>\r\n");
      out.write("<td><form><input type=\"submit\"  name=\"rthree\" value=\"Remove\" style=\"width:100%\"></form></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>ICS 111</td>\r\n");
      out.write("<td> Subject Description </td>\r\n");
      out.write("<td>3</td>\r\n");
      out.write("<td>1</td>\r\n");
      out.write("<td>Section</td>\r\n");
      out.write("<td>Schedule</td>\r\n");
      out.write("<td><form><input type=\"submit\"  name=\"rfour\" value=\"Remove\" style=\"width:100%\"></form></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>PE</td>\r\n");
      out.write("<td> Subject Description </td>\r\n");
      out.write("<td>3</td>\r\n");
      out.write("<td>Lab Units</td>\r\n");
      out.write("<td>Section</td>\r\n");
      out.write("<td>Schedule</td>\r\n");
      out.write("<td><form><input type=\"submit\"  name=\"rfive\" value=\"Remove\" style=\"width:100%\"></form></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>NSTP</td>\r\n");
      out.write("<td> Subject Description </td>\r\n");
      out.write("<td>3</td>\r\n");
      out.write("<td>Lab Units</td>\r\n");
      out.write("<td>Section</td>\r\n");
      out.write("<td>Schedule</td>\r\n");
      out.write("<td><form><input type=\"submit\"  name=\"rsix\" value=\"Remove\" style=\"width:100%\"></form></td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("<br>\r\n");
      out.write("<table border=\"1\" align=\"right\" style=\"width: 25%\">\r\n");
      out.write("<tr>\r\n");
      out.write("<th> Available Petition Subject (Approved)</th>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td> (3 Units) MATH 101 F 7-10 </td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td> <form><input type=\"submit\" name=\"two\"  value=\"Add schedule to subjects\" align=\"center\"/></form></td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("<table align=\"center\">\r\n");
      out.write("<tr>\r\n");
      out.write("\t<th>TOTAL UNITS:</th>\r\n");
      out.write("\t<th>19 Units</th> \r\n");
      out.write("\t<th><a href=\"submit.jsp\"> SUBMIT</a>\r\n");
      out.write("</table>\r\n");
      out.write("<br><br>\r\n");
      out.write("<p>*Schedule will not be submitted if above 24 unit</p>\r\n");
      out.write("<p>*Subjects cannot be added if there are conflicts in the schedule</p>\r\n");
      out.write("<style>\r\n");
      out.write("h1 {\r\n");
      out.write("\tfont-family: consolas;\r\n");
      out.write("\tfont-size: 300%;\r\n");
      out.write("\tcolor: blue;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h2 {\r\n");
      out.write("\tfont-family: calibri;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("p {\r\n");
      out.write("\tfont-family: \"verdana\";\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=\"text\"] {\r\n");
      out.write("\tbackground: white;\r\n");
      out.write("\tborder: 1px double black;\r\n");
      out.write("\tborder-radius: 5px;\r\n");
      out.write("\tbox-shadow: 0 0 5px yellow;\r\n");
      out.write("\tcolor: black;\r\n");
      out.write("\toutline: center;\r\n");
      out.write("\theight: 25px;\r\n");
      out.write("\twidth: 275px;\r\n");
      out.write("\tfont-family: \"verdana\";\r\n");
      out.write("}\r\n");
      out.write("table, th, td {\r\n");
      out.write("border: 1px solid black;\r\n");
      out.write("border-collapse: collapse;\r\n");
      out.write("}\r\n");
      out.write("th, td {\r\n");
      out.write("padding: 4px;\r\n");
      out.write("text-align: center;\r\n");
      out.write("font-family: calibri;  \r\n");
      out.write("}\r\n");
      out.write("input[type=\"submit\"]{\r\n");
      out.write("    background: #87CEFA; \r\n");
      out.write("    border: 1px double #DDD; \r\n");
      out.write("    border-radius: 5px; \r\n");
      out.write("    box-shadow: 0 0 5px #333; \r\n");
      out.write("    color: ; \r\n");
      out.write("    outline: none; \r\n");
      out.write("    font-family: \"verdana\";\r\n");
      out.write("    font-color: black;\r\n");
      out.write("    height: 25px;\r\n");
      out.write("}\r\n");
      out.write("input.remove{\r\n");
      out.write("\theight:30em; \r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
